#include<iostream>
using namespace std;
int main()
{
    string en, sn, br, sem, mn;
    int m, p, cpf, tom, tm, tmps, result;
    float avg, per;
    cout<<"*****************************************************************"<<endl;
    cout<<"                STUDENT RECORD MANAGEMENT SYSTEM                 "<<endl;
    cout<<"*****************************************************************"<<endl;
    cout<<endl;
    cout<<"Software Version : 1.2"<<endl;
    cout<<endl;
    cout<<endl;
    cout<<"----------------------------------------------------------------"<<endl;
    cout<<"                     STUDENT'S REGISTRATION                     "<<endl;
    cout<<"----------------------------------------------------------------"<<endl;
    cout<<endl;
    cout<<"Enter Enrollment Number : ";
    cin>>en;
    cout<<"Enter Student Name : ";
    cin.ignore();
    getline(cin, sn);
    cout<<"Enter Branch : ";
    cin>>br;
    cout<<"Enter Semester : ";
    cin>>sem;
    cout<<"Enter Mobile Number : ";
    cin>>mn;
    cout<<endl;
    cout<<endl;
    cout<<"----------------------------------------------------------------"<<endl;
    cout<<"                         STUDENT'S DETAILS                      "<<endl;
    cout<<"----------------------------------------------------------------"<<endl;
    cout<<endl;
    cout<<"Student's Enrollment Number : "<<en<<endl;
    cout<<"Student's Name              : "<<sn<<endl;
    cout<<"Student's Branch            : "<<br<<endl;
    cout<<"Student's Semester          : "<<sem<<endl;
    cout<<"Student's Mobile Number     : "<<mn<<endl;
    cout<<endl;
    cout<<endl;
    cout<<"----------------------------------------------------------------"<<endl;
    cout<<"                      ACEDAMIC INFORMATION                      "<<endl;
    cout<<"----------------------------------------------------------------"<<endl;
    cout<<endl;
    cout<<"Please Enter Total Marks Per Subject : ";
    cin>>tmps;
    cout<<"Enter Mathematics Marks : ";
    cin>>m;
    cout<<"Enter Physics Marks : ";
    cin>>p;
    cout<<"Enter Computer Programming Foundation Marks : ";
    cin>>cpf;
    tom = m+p+cpf;
    avg = (float)tom/3;
    tm = tmps*3;
    per = (float)(tom*100)/tm;
    cout<<endl;
    cout<<"----------------------------------------------------------------"<<endl;
    cout<<"                         ACEDAMIC SUMMARY                       "<<endl;
    cout<<"----------------------------------------------------------------"<<endl;
    cout<<endl;
    cout<<"Total Marks   : "<<tom<<endl;
    cout<<"Average Marks : "<<avg<<endl;
    cout<<"Percentage    : "<<per<<"%"<<endl;
    cout<<"----------------------------------------------------------------"<<endl;

    cout<<"                                          ~developed by Om Patel"<<endl;
    return 0;
}
